CrudMvcComAdo/Models/Times.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CrudMvcComAdo.Models
{
    public class Times
    {
        [Display(Name = "Id")]
        public int TimesId { get; set; }

        [Required(ErrorMessage ="Informe o nome do time")]
        public string Time { get; set; }

        [Required(ErrorMessage = "Informe o estado do time")]
        [Display(Name = "Estado")]
        public string EstadoSigla { get; set; }

        public int EstadoId { get; set; }

        public string EstadoNome { get; set; }

        [Required(ErrorMessage = "Informe as cores do time")]
        public string Cores { get; set; }
    }
}

CrudMvcComAdo/Controllers/TimeController.cs
using CrudMvcComAdo.Models;
using CrudMvcComAdo.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrudMvcComAdo.Controllers
{
    public class TimeController : Controller
    {
        // GET: Time

        private TimeRepositorio _repositorio;

        private TimeRepositorio _repositorioEstado;

        [HttpGet]
        public ActionResult ObterTimes()
        {
            _repositorio = new TimeRepositorio();

            _repositorio.ObterTimes();
            ModelState.Clear();

            return View(_repositorio.ObterTimes());
        }

        //Incluir

        [HttpGet]
        public ActionResult IncluirTime()
        {
            _repositorio = new TimeRepositorio();

            ViewBag.EstadoId = new SelectList(_repositorio.ObterEstados(), "EstadoId", "EstadoSigla", "1");

            return View();
        }

        [HttpPost]
        public ActionResult IncluirTime(Times timeObj)
        {
            try
            {
                _repositorio = new TimeRepositorio();

                
                    if (_repositorio.AdicionarTime(timeObj))
                    {
                        ViewBag.Mensagem = "Time cadastrado com sucesso";
                    }
                

                ViewBag.EstadoId = new SelectList(_repositorio.ObterEstados(), "EstadoId", "EstadoSigla", "1");

                //return RedirectToAction("ObterTimes");

                return View();
            }
            catch (Exception)
            {
                return View("ObterTimes");
            }
        }


        //Editar

        [HttpGet]
        public ActionResult EditarTime(int id)
        {
            _repositorio = new TimeRepositorio();

            _repositorioEstado = new TimeRepositorio();

            var estadoAtual = _repositorio.ObterTimes().Find(t => t.TimesId == id).EstadoId;

            ViewBag.EstadoId = new SelectList(_repositorioEstado.ObterEstados(), "EstadoId", "EstadoSigla", estadoAtual);

            return View(_repositorio.ObterTimes().Find(t => t.TimesId == id));
        }

        [HttpPost]
        public ActionResult EditarTime(int id, Times timeObj)
        {
            try
            {
                _repositorio = new TimeRepositorio();

                _repositorioEstado = new TimeRepositorio();

                _repositorio.AtualizarTime(timeObj);

                ViewBag.EstadoId = new SelectList(_repositorioEstado.ObterEstados(), "EstadoId", "EstadoSigla", "1");

                return RedirectToAction("ObterTimes");
            }
            catch (Exception)
            {
                return View("ObterTimes");
            }
        }
   
        public ActionResult ExcluirTime(int id)
        {
            try
            {
                _repositorio = new TimeRepositorio();
                if (_repositorio.ExcluirTime(id))
                {
                    ViewBag.Mensagem = "Time excluído com sucesso";
                }

                return RedirectToAction("Obtertimes");
            }
            catch (Exception)
            {
                return View("ObterTimes");
            }
        }
    }
}

CrudMvcComAdo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CRUD USANDO ASP.NET MVC E ADO.NET</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("CRUD", "ObterTimes", "Time", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CRUD USANDO ASP.NET MVC E ADO.NET</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

CrudMvcComAdo/Views/Time/EditarTime.cshtml
@model CrudMvcComAdo.Models.Times

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Times</h4>
    <hr />
    <div>
        @Html.ActionLink("Listar todos os times", "ObterTimes")
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TimesId)

    <div class="form-group">
        @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.EstadoSigla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadoSigla, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadoSigla, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.EstadoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadoId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadoId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <div style="margin-left: 210px">
                    @Html.DropDownList("EstadoId")
                </div>
            </div>
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.EstadoNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadoNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadoNome, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Cores, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cores, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cores, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

CrudMvcComAdo/Views/Time/IncluirTime.cshtml
@model CrudMvcComAdo.Models.Times

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Times</h4>
    <hr />
    <div>
        @Html.ActionLink("Listar todos os times", "ObterTimes")
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.EstadoSigla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadoSigla, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadoSigla, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.EstadoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadoId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadoId, "", new { @class = "text-danger" })
            </div>

        </div>*@
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <div style="margin-left: 210px">
                    @Html.DropDownList("EstadoId")
                </div>
            </div>
        </div>
    </div>
    @*<div class="form-group">
            @Html.LabelFor(model => model.EstadoNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadoNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadoNome, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Cores, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cores, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cores, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" style="color:green">
            @ViewBag.Mensagem
        </div>
    </div>
</div>
    }

CrudMvcComAdo/Views/Time/ObterTimes.cshtml
@model IEnumerable<CrudMvcComAdo.Models.Times>

<p>
    @Html.ActionLink("Cadastrar novo time", "IncluirTime")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstadoSigla)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cores)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstadoSigla)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cores)
        </td>
        <td>
            @Html.ActionLink("Editar", "EditarTime", new { id=item.TimesId }) |
            @Html.ActionLink("Deletar", "ExcluirTime", new { id=item.TimesId },new { onclick = "return confirm('Tem certeza que deseja excluir?');" })
        </td>
    </tr>
}

</table>